pyflakes:
  disable:
    - F821

pylint:
  disable:
    - import-error
    - import-outside-toplevel
    - inconsistent-return-statements
    - logging-not-lazy
    - no-else-return
    - not-a-mapping
    - protected-access
    - relative-beyond-top-level
    - signature-differs
    - too-many-ancestors
    - too-many-return-statements
