pyflakes:
  disable:
    - F821

pylint:
  disable:
    - import-outside-toplevel
    - no-else-return
    - not-a-mapping
    - protected-access
    - relative-beyond-top-level
    - signature-differs
    - too-many-ancestors
