[tool.poetry]
name = 'h1st'
version = '0.1.13'
description = 'Human-First AI (H1st)'
authors = ['h1st-ai <engineering@aitomatic.com>']
license = 'Apache-2.0'
readme = 'README.md'
homepage = 'https://h1st.ai'
repository = 'https://github.com/h1st-ai/h1st'
include = ['h1st/*']


[tool.poetry.dependencies]
Python = '>= 3.8, < 3.11'

# Data Processing
PyArrow = '^9.0.0'
S3FS = '^2022.8.2'

# Machine Learning / Deep Learning
SciKit-Fuzzy = '^0.4.2'
SciKit-Learn = '^1.1.2'
TensorFlow = '^2.10.0'

# Trustworthy AI
GraphViz = '^0.20.1'
LIME = '^0.2.0.1'
SHAP = '^0.41.0'

# misc/other
PyYAML = '^6.0'
ULID-Py = '^1.1.0'


[tool.poetry.dev-dependencies]
Commitizen = '^2.32.4'
Pre-Commit = '^2.20.0'
PyLint = '^2.15.2'
PyTest = '^7.1.3'
Sphinx = '^5.1.1'
Sphinx-RtD-Theme = '^1.0.0'


[build-system]
requires = [
  'Poetry-Core >= 1.1.0',
]
build-backend = 'poetry.core.masonry.api'


[tool.pylint.format]
max-line-length = 120
