[tool.poetry]
name = "h1st"
version = "0.0.6.dev1"
description = "Human-First AI (H1ST)"
authors = ["h1st-ai <engineering@aitomatic.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://h1st.ai"
repository = "https://github.com/h1st-ai/h1st"
include = ["h1st/*"]

[tool.poetry.dependencies]
# PYTHON
Python = '^3.8'

# DATA MANAGEMENT & PROCESSING
NumPy = '< 1.20'   # too low-level to specify?
Pandas = '^1.3.3'
PyArrow = '^5.0.0'
Ray = {extras = ['tune'], version = '^1.6.0'}

# MACHINE LEARNING / DEEP LEARNING
Auto-SKLearn = '^0.14.0'
# SciKit-Learn = '^1.0'

TensorFlow = '^2.6.0'
TensorFlow-Hub = '^0.12.0'

Torch = '^1.9.1'
Torch-Model-Archiver = '^0.4.2'
TorchServe = '^0.4.2'
TorchText = '^0.10.1'
TorchVision = '^0.10.1'

Transformers = '^4.11.2'
SentencePiece = '^0.1.96'   # Translation
TIMM = '^0.4.12'   # for Object Detection

# HYPER-PARAMETER TUNING
Bayesian-Optimization = '^1.2.0'
ConfigSpace = '^0.4.20'
Hpbandster = '^0.7.4'
Tabulate = '^0.8.9'

# CLOUD SERVICES
Google-Cloud-Translate = '^3.4.1'
GoogleTrans = '^4.0.0rc1'

# FUZZY LOGIC
SciKit-Fuzzy = '^0.4.2'

# TRUSTWORTHY AI
LIME = '^0.2.0.1'
SHAP = '^0.39.0'

# GRAPH PROCESSING
GraphViz = '^0.17'

# MODEL REPOSITORY
CloudPickle = '^2.0.0'
JobLib = '^1.0.1'
S3FS = '^2021.10.0'
ULID-Py = '^1.1.0'

# CLI
Click = '^7.1.2'   # aligned with Streamlit
Colored = '^1.4.2'

# DJANGO
Django = '^3.2.7'

# Django Polymorphic Models
Django-Polymorphic = '^3.0.0'

# Django Admin Themes
Django-Jazzmin = '^2.4.8'

# Django Autocomplete
Django-Autocomplete-Light = '^3.8.2'

# Django REST Framework
DjangoRESTFramework = '^3.12.4'
CoreAPI = '^2.3.3'   # closely related to Django REST Framework

# Django Filtering
Django-Filter = '^21.1'
DjangoRESTFramework-Filters = '1.0.0.dev2'

# Django Model Query Optimization
Django-Model-Query-Graphs = '^0.0.5'

# Django Query Profiling
Django-Query-Profiler = '^0.8'
Django-Silk = '^4.1.0'

# Django Extensions & Utilities
Django-Extensions = '^3.1.3'
Django-Model-Utils = '^4.1.1'
Django-Storages = '^1.11.1'

# Django CORS Headers
Django-CORS-Headers = '^3.9.0'

# UI
Gradio = '^2.3.6'
Streamlit = '^1.0.0'
Watchdog = '^2.1.6'   # better performance for Streamlit

# DATABASE CONNECTORS/DRIVERS
MySQLClient = '^2.0.3'
PsycoPG2-binary = '^2.9.1'

# OTHER
Cython = '^0.29.24'
GitPython = '^3.1.24'
Pillow = '^8.3.2'
# Pillow-SIMD = '^7.0.0'   # complex to install
'Ruamel.YAML' = '^0.17.16'
PSUtil = '^5.8.0'
Python-DotEnv = '^0.19.1'
Requests = '^2.26.0'
Tqdm = '^4.62.3'


[tool.poetry.dev-dependencies]
commitizen = "^2.19.0"
pytest = "^6.2.5"
pre-commit = "^2.15.0"
tensorflow = "^2.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
