# Generated by Django 3.2.6 on 2021-08-19 18:20


import json.decoder
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0007_optional_unique_name')]

    operations = [
        migrations.AddField(
            model_name='model',
            name='params',
            field=models.JSONField(
                blank=True,
                decoder=json.decoder.JSONDecoder,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text='Paramemeters',
                null=True,
                verbose_name='Paramemeters')
        )
    ]
