# Generated by Django 3.2.7 on 2021-09-30 07:05


import django.core.serializers.json
from django.db import migrations, models
import json.decoder


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0008_ModelParams')]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='artifact'),

        migrations.AddField(
            model_name='mlmodel',
            name='artifact_local_path',
            field=models.CharField(
                db_index=True,
                default=None,
                help_text='ML Model Artifact Local Path',
                max_length=255,
                verbose_name='ML Model Artifact Local Path')),

        migrations.AlterField(
            model_name='model',
            name='params',
            field=models.JSONField(
                blank=True,
                decoder=json.decoder.JSONDecoder,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text='Model Parameters',
                null=True,
                verbose_name='Model Parameters'))
    ]
