# Generated by Django 3.2.7 on 2021-09-30 09:56


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0010_MLModel_artifact_global_url')]

    operations = [
        migrations.CreateModel(
            name='PyLoadablePreTrainedMLModel',

            fields=[
                ('mlmodel_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name='h1st_py_loadable_pretrained_ml_models',
                     serialize=False,
                     to='H1stModel.mlmodel')),

                ('py_loader_module_and_qualname',
                 models.CharField(
                     db_index=True,
                     default=None,
                     help_text=('Pretrained ML Model Python Loader '
                                '(module.qualname)'),
                     max_length=255,
                     verbose_name=('Pretrained ML Model Python Loader '
                                   '(module.qualname)')))
            ],

            options={
                'verbose_name':
                    'H1st Python-Loadable Pre-Trained ML Model',
                'verbose_name_plural':
                    'H1st Python-Loadable Pre-Trained ML Models',
                'db_table': 'H1stModel_PyLoadablePreTrainedMLModel',
                'abstract': False,
                'default_related_name':
                    'h1st_py_loadable_pretrained_ml_models',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.mlmodel',)
        )
    ]
