# Generated by Django 3.2.7 on 2021-09-30 10:20


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0011_PyLoadablePreTrainedMLModel')]

    operations = [
        migrations.CreateModel(
            name='HuggingFacePreTrainedTransformer',

            fields=[
                ('pyloadablepretrainedmlmodel_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name='h1st_hugging_face_pretrained_transformers',
                     serialize=False,
                     to='H1stModel.pyloadablepretrainedmlmodel'))
            ],

            options={
                'verbose_name': 'H1st Hugging Face Pre-Trained Transformer',
                'verbose_name_plural':
                    'H1st Hugging Face Pre-Trained Transformers',
                'db_table': 'H1stModel_HuggingFacePreTrainedTransformer',
                'abstract': False,
                'default_related_name':
                    'h1st_hugging_face_pretrained_transformers',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.pyloadablepretrainedmlmodel',)
        )
    ]
