# Generated by Django 3.2.7 on 2021-09-30 22:04


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('H1stTrust', '0002_optional_unique_name'),
        ('H1stModel', '0012_HuggingFacePreTrainedTransformer')
    ]

    operations = [
        migrations.CreateModel(
            name='PreTrainedHuggingFaceTransformer',

            fields=[
                ('pyloadablepretrainedmlmodel_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name='h1st_pretrained_hugging_face_transformers',
                     serialize=False,
                     to='H1stModel.pyloadablepretrainedmlmodel'))
            ],

            options={
                'verbose_name':
                    'H1st Pre-Trained Hugging Face Transformer',
                'verbose_name_plural':
                    'H1st Pre-Trained Hugging Face Transformers',
                'db_table': 'H1stModel_PreTrainedHuggingFaceTransformer',
                'abstract': False,
                'default_related_name':
                    'h1st_pretrained_hugging_face_transformers',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.pyloadablepretrainedmlmodel',)
        ),

        migrations.DeleteModel(
            name='HuggingFacePreTrainedTransformer')
    ]
