# Generated by Django 3.2.7 on 2021-10-01 00:43


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0013_PretrainedHuggingFaceTransformer')]

    operations = [
        migrations.AlterField(
            model_name='pyloadablepretrainedmlmodel',
            name='py_loader_module_and_qualname',
            field=models.CharField(
                db_index=True,
                default=None,
                help_text=('Pre-Trained ML Model Python Loader '
                           '(module.qualname)'),
                max_length=255,
                verbose_name='Pre-Trained ML Model Python Loader'))
    ]
