# Generated by Django 3.2.7 on 2021-10-01 06:30


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0015_PreTrainedKerasImageNetClassifier')]

    operations = [
        migrations.AlterModelOptions(
            name='pretrainedkerasimagenetclassifier',
            options={
                'base_manager_name': 'objects',
                'default_related_name':
                    'h1st_pretrained_keras_imagenet_classifiers',
                'verbose_name': 'Pre-Trained Keras ImageNet Classifier',
                'verbose_name_plural': 'Pre-Trained Keras ImageNet Classifiers'
            }),

        migrations.AlterField(
            model_name='pretrainedkerasimagenetclassifier',
            name='pyloadablepretrainedmlmodel_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name='h1st_pretrained_keras_imagenet_classifiers',
                serialize=False,
                to='H1stModel.pyloadablepretrainedmlmodel')),

        migrations.AlterModelTable(
            name='pretrainedkerasimagenetclassifier',
            table='H1stModel_PreTrainedKerasImageNetClassifier')
    ]
