# Generated by Django 3.2.7 on 2021-10-09 04:07


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('H1stModel',
         '0018_GoogleCloudTranslationServiceModel_GoogleTranslateServiceModel'
         )
    ]

    operations = [
        migrations.CreateModel(
            name='PreTrainedTorchImageNetClassifier',

            fields=[
                ('pyloadablepretrainedmlmodel_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name='h1st_pretrained_torch_imagenet_classifiers',
                     serialize=False,
                     to='H1stModel.pyloadablepretrainedmlmodel'))
            ],

            options={
                'verbose_name': 'Pre-Trained Torch ImageNet Classifier',
                'verbose_name_plural':
                    'Pre-Trained Torch ImageNet Classifiers',
                'db_table': 'H1stModel_PreTrainedTorchImageNetClassifier',
                'abstract': False,
                'default_related_name':
                    'h1st_pretrained_torch_imagenet_classifiers',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.pyloadablepretrainedmlmodel',)
        )
    ]
