# Generated by Django 3.2.7 on 2021-10-09 22:31


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0019_PreTrainedTorchImageNetClassifier')]

    operations = [
        migrations.CreateModel(
            name='PreTrainedTFHubTransformer',

            fields=[
                ('pyloadablepretrainedmlmodel_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name='h1st_pretrained_tf_hub_transformers',
                     serialize=False,
                     to='H1stModel.pyloadablepretrainedmlmodel'))
            ],

            options={
                'verbose_name': 'H1st Pre-Trained TensorFlow Hub Transformer',
                'verbose_name_plural':
                    'H1st Pre-Trained TensorFlow Hub Transformers',
                'db_table': 'H1stModel_PreTrainedTFHubTransformer',
                'abstract': False,
                'default_related_name': 'h1st_pretrained_tf_hub_transformers',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.pyloadablepretrainedmlmodel',)
        )
    ]
