# Generated by Django 3.2.7 on 2021-10-10 00:12


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('H1stModel', '0021_PreTrainedHuggingFaceImageClassifier')
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='artifact_local_path',
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text='ML Model Artifact Local Path',
                max_length=255,
                null=True,
                verbose_name='ML Model Artifact Local Path'))
    ]
