# Generated by Django 3.2.7 on 2021-10-10 00:19


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0022_MLModel_artifact_local_path')]

    operations = [
        migrations.AlterModelOptions(
            name='pretrainedhuggingfacetransformer',

            options={
                'base_manager_name': 'objects',
                'default_related_name':
                    'h1st_pretrained_hugging_face_transformers',
                'verbose_name': 'Pre-Trained Hugging Face Transformer',
                'verbose_name_plural': 'Pre-Trained Hugging Face Transformers'
            }
        )
    ]
