# Generated by Django 3.2.7 on 2021-10-10 00:45


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('H1stTrust', '0002_optional_unique_name'),
        ('H1stModel', '0023_PreTrainedHuggingFaceTransformer_options')
    ]

    operations = [
        migrations.RenameModel(
            old_name='PreTrainedTorchImageNetClassifier',
            new_name='PreTrainedTorchVisionImageNetClassifier'),

        migrations.AlterModelTable(
            name='pretrainedtorchvisionimagenetclassifier',
            table='H1stModel_PreTrainedTorchVisionImageNetClassifier')
    ]
