# Generated by Django 3.2.7 on 2021-10-10 00:46


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('H1stModel', '0024_PreTrainedTorchVisionImageNetClassifier')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pretrainedtorchvisionimagenetclassifier',
            options={
                'base_manager_name': 'objects',
                'default_related_name':
                    'h1st_pretrained_torch_vision_imagenet_classifiers',
                'verbose_name': 'Pre-Trained Torch Vision ImageNet Classifier',
                'verbose_name_plural':
                    'Pre-Trained Torch Vision ImageNet Classifiers'}),

        migrations.AlterField(
            model_name='pretrainedtorchvisionimagenetclassifier',
            name='pyloadablepretrainedmlmodel_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name=('h1st_pretrained_'
                              'torch_vision_imagenet_classifiers'),
                serialize=False,
                to='H1stModel.pyloadablepretrainedmlmodel'))
    ]
