# Generated by Django 3.2.8 on 2021-10-15 23:05


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0028_PreTrainedHuggingFaceObjectDetector')]

    operations = [
        migrations.CreateModel(
            name='PreTrainedHuggingFaceText2TextGenerator',

            fields=[
                ('pretrainedhuggingfacetransformer_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name=('h1st_pretrained_'
                                   'hugging_face_text2text_generators'),
                     serialize=False,
                     to='H1stModel.pretrainedhuggingfacetransformer'))
            ],

            options={
                'verbose_name':
                    'Pre-Trained Hugging Face Text-to-Text Generator',
                'verbose_name_plural':
                    'Pre-Trained Hugging Face Text-to-Text Generators',
                'db_table':
                    'H1stModel_PreTrainedHuggingFaceText2TextGenerator',
                'abstract': False,
                'default_related_name':
                    'h1st_pretrained_hugging_face_text2text_generators',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.pretrainedhuggingfacetransformer',)
        )
    ]
