# Generated by Django 3.2.8 on 2021-10-16 22:21


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0032_PreTrainedHuggingFaceTranslator')]

    operations = [
        migrations.CreateModel(
            name='PreTrainedHuggingFaceSpeechRecognizer',

            fields=[
                ('pretrainedhuggingfacetransformer_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name=('h1st_pretrained_'
                                   'hugging_face_speech_recognizers'),
                     serialize=False,
                     to='H1stModel.pretrainedhuggingfacetransformer'))
            ],

            options={
                'verbose_name': 'Pre-Trained Hugging Face Speech Recognizer',
                'verbose_name_plural':
                    'Pre-Trained Hugging Face Speech Recognizers',
                'db_table': 'H1stModel_PreTrainedHuggingFaceSpeechRecognizer',
                'abstract': False,
                'default_related_name':
                    'h1st_pretrained_hugging_face_speech_recognizers',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.pretrainedhuggingfacetransformer',)
        )
    ]
