# Generated by Django 3.2.8 on 2021-10-17 04:56


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('H1stModel', '0034_PreTrainedHuggingFaceAudioClassifier')
    ]

    operations = [
        migrations.CreateModel(
            name='PreTrainedHuggingFaceMaskFiller',

            fields=[
                ('pretrainedhuggingfacetransformer_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name='h1st_pretrained_hugging_face_mask_fillers',
                     serialize=False,
                     to='H1stModel.pretrainedhuggingfacetransformer'))
            ],

            options={
                'verbose_name': 'Pre-Trained Hugging Face Mask Filler',
                'verbose_name_plural': 'Pre-Trained Hugging Face Mask Fillers',
                'db_table': 'H1stModel_PreTrainedHuggingFaceMaskFiller',
                'abstract': False,
                'default_related_name':
                    'h1st_pretrained_hugging_face_mask_fillers',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.pretrainedhuggingfacetransformer',)
        )
    ]
