# Generated by Django 3.2.8 on 2021-10-17 10:57


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('H1stModel', '0036_PreTrainedHuggingFaceZeroShotClassifier')
    ]

    operations = [
        migrations.CreateModel(
            name='PreTrainedHuggingFaceQuestionAnswerer',

            fields=[
                ('pretrainedhuggingfacetransformer_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name=('h1st_pretrained_'
                                   'hugging_face_question_answerers'),
                     serialize=False,
                     to='H1stModel.pretrainedhuggingfacetransformer'))
            ],

            options={
                'verbose_name': 'Pre-Trained Hugging Face Question Answerer',
                'verbose_name_plural':
                    'Pre-Trained Hugging Face Question Answerers',
                'db_table': 'H1stModel_PreTrainedHuggingFaceQuestionAnswerer',
                'abstract': False,
                'default_related_name':
                    'h1st_pretrained_hugging_face_question_answerers',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.pretrainedhuggingfacetransformer',)
        ),

        migrations.CreateModel(
            name='PreTrainedHuggingFaceTableQuestionAnswerer',

            fields=[
                ('pretrainedhuggingfacetransformer_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name=('h1st_pretrained_'
                                   'hugging_face_table_question_answerers'),
                     serialize=False,
                     to='H1stModel.pretrainedhuggingfacetransformer'))
            ],

            options={
                'verbose_name':
                    'Pre-Trained Hugging Face Table Question Answerer',
                'verbose_name_plural':
                    'Pre-Trained Hugging Face Table Question Answerers',
                'db_table':
                    'H1stModel_PreTrainedHuggingFaceTableQuestionAnswerer',
                'abstract': False,
                'default_related_name':
                    'h1st_pretrained_hugging_face_table_question_answerers',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.pretrainedhuggingfacetransformer',)
        )
    ]
