# Generated by Django 3.1.13 on 2021-07-19 23:22


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('H1stModel', '0006_kerasmodel_tfmodel_torchmodel')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'default_related_name': 'h1st_models',
                'get_latest_by': 'modified',
                'managed': True,
                'ordering': ('name', '-modified'),
                'permissions': (),
                'select_on_save': False,
                'verbose_name': 'H1st Model',
                'verbose_name_plural': 'H1st Models'}),

        migrations.AddField(
            model_name='model',
            name='name',
            field=models.CharField(
                    blank=True,
                    db_index=True,
                    default=None,
                    help_text='(optional) Unique Name',
                    max_length=255,
                    null=True,
                    unique=True,
                    verbose_name='(optional) Unique Name'))
    ]
