# Generated by Django 3.2.7 on 2021-10-03 23:51


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('H1stModel', '0016_PreTrainedKerasImageNetClassifier')]

    operations = [
        migrations.CreateModel(
            name='CloudServiceModel',

            fields=[
                ('model_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name='h1st_cloud_svc_models',
                     serialize=False,
                     to='H1stModel.model'))
            ],

            options={
                'verbose_name': 'Cloud-Service Model',
                'verbose_name_plural': 'Cloud-Service Models',
                'db_table': 'H1stModel_CloudServiceModel',
                'abstract': False,
                'default_related_name': 'h1st_cloud_svc_models',
                'base_manager_name': 'objects'
            },

            bases=('H1stModel.model',)
        )
    ]
