# Generated by Django 3.1.13 on 2021-07-19 21:47


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('H1stData', '0003_NumPyArray_PandasDataFrame')
    ]

    operations = [
        migrations.AlterField(
            model_name='namedcsvdataset',
            name='name',
            field=models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Unique Name')),

        migrations.AlterField(
            model_name='namedjsondataset',
            name='name',
            field=models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Unique Name')),

        migrations.AlterField(
            model_name='namednumpyarray',
            name='name',
            field=models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Unique Name')),

        migrations.AlterField(
            model_name='namedpandasdataframe',
            name='name',
            field=models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Unique Name')),

        migrations.AlterField(
            model_name='namedparquetdataset',
            name='name',
            field=models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Unique Name')),

        migrations.AlterField(
            model_name='namedtfrecorddataset',
            name='name',
            field=models.CharField(
                    db_index=True,
                    default=None,
                    help_text='Unique Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Unique Name'))
    ]
