# Generated by Django 3.1.13 on 2021-07-19 23:22


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('H1stData', '0004_NamedDataSet')
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataschema',
            options={
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'default_related_name': 'data_schemas',
                'managed': True,
                'ordering': ('name',),
                'permissions': (),
                'select_on_save': False,
                'verbose_name': 'Data Schema',
                'verbose_name_plural': 'Data Schemas'}),

        migrations.AlterModelOptions(
            name='dataset',
            options={
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'default_related_name': 'data_sets',
                'get_latest_by': 'modified',
                'managed': True,
                'ordering': ('name', '-modified'),
                'permissions': (),
                'select_on_save': False,
                'verbose_name': 'Data Set',
                'verbose_name_plural': 'Data Sets'}),

        migrations.AlterModelOptions(
            name='namedcsvdataset',
            options={
                'base_manager_name': 'objects',
                'default_related_name': 'named_csv_data_sets',
                'verbose_name': 'Named CSV Data Set',
                'verbose_name_plural': 'Named CSV Data Sets'}),

        migrations.AlterModelOptions(
            name='namedjsondataset',
            options={
                'base_manager_name': 'objects',
                'default_related_name': 'named_json_data_sets',
                'verbose_name': 'Named JSON Data Set',
                'verbose_name_plural': 'Named JSON Data Sets'}),

        migrations.AlterModelOptions(
            name='namednumpyarray',
            options={
                'base_manager_name': 'objects',
                'default_related_name': 'named_numpy_arrays',
                'verbose_name': 'Named NumPy Array',
                'verbose_name_plural': 'Named NumPy Arrays'}),

        migrations.AlterModelOptions(
            name='namedpandasdataframe',
            options={
                'base_manager_name': 'objects',
                'default_related_name': 'named_pandas_dataframes',
                'verbose_name': 'Named Pandas DataFrame',
                'verbose_name_plural': 'Named Pandas DataFrames'}),

        migrations.AlterModelOptions(
            name='namedparquetdataset',
            options={
                'base_manager_name': 'objects',
                'default_related_name': 'named_parquet_data_sets',
                'verbose_name': 'Named Parquet Data Set',
                'verbose_name_plural': 'Named Parquet Data Sets'}),

        migrations.AlterModelOptions(
            name='namedtfrecorddataset',
            options={
                'base_manager_name': 'objects',
                'default_related_name': 'named_tfrecord_data_sets',
                'verbose_name': 'Named TFRecord Data Set',
                'verbose_name_plural': 'Named TFRecord Data Sets'}),

        migrations.RemoveField(
            model_name='dataschema',
            name='created'),
        migrations.RemoveField(
            model_name='dataschema',
            name='modified'),

        migrations.RemoveField(
            model_name='namedcsvdataset',
            name='name'),
        migrations.RemoveField(
            model_name='namedjsondataset',
            name='name'),
        migrations.RemoveField(
            model_name='namednumpyarray',
            name='name'),
        migrations.RemoveField(
            model_name='namedpandasdataframe',
            name='name'),
        migrations.RemoveField(
            model_name='namedparquetdataset',
            name='name'),
        migrations.RemoveField(
            model_name='namedtfrecorddataset',
            name='name'),

        migrations.AddField(
            model_name='dataset',
            name='name',
            field=models.CharField(
                    blank=True,
                    db_index=True,
                    default=None,
                    help_text='(optional) Unique Name',
                    max_length=255,
                    null=True,
                    unique=True,
                    verbose_name='(optional) Unique Name'))
    ]
