# Generated by Django 3.2.7 on 2021-10-11 06:43


import django.core.serializers.json
from django.db import migrations, models
import json.decoder


class Migration(migrations.Migration):
    dependencies = [('H1stData', '0009_DataSet_global_url_and_local_path')]

    operations = [
        migrations.AlterField(
            model_name='jsondataset',
            name='in_db_json',
            field=models.JSONField(
                blank=True,
                decoder=json.decoder.JSONDecoder,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text='In-Database JSON Data Content',
                null=True,
                verbose_name='In-Database JSON Data Content'))
    ]
