# Generated by Django 3.2.7 on 2021-10-11 07:11


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('H1stData', '0010_JSONDataSet_in_db_json')]

    operations = [
        migrations.RemoveField(
            model_name='csvdataset',
            name='is_dir'),
        migrations.RemoveField(
            model_name='csvdataset',
            name='path'),
        migrations.RemoveField(
            model_name='parquetdataset',
            name='is_dir'),
        migrations.RemoveField(
            model_name='parquetdataset',
            name='path'),
        migrations.RemoveField(
            model_name='tfrecorddataset',
            name='is_dir'),
        migrations.RemoveField(
            model_name='tfrecorddataset',
            name='path')
    ]
