# Generated by Django 3.2.7 on 2021-10-11 08:12


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('H1stData', '0011_remove_FileStoredDataSet')]

    operations = [
        migrations.RenameField(
            model_name='textdataset',
            old_name='text',
            new_name='in_db_text')
    ]
