# Generated by Django 3.2.7 on 2021-10-11 08:13


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('H1stData', '0012_TextDataSet_in_db_text')]

    operations = [
        migrations.AlterField(
            model_name='textdataset',
            name='in_db_text',
            field=models.TextField(blank=True,
                                   default=None,
                                   help_text='In-Database Text Data Content',
                                   null=True,
                                   verbose_name='In-Database Text Data Content'
                                   ))
    ]
