# Generated by Django 3.2.7 on 2021-10-11 08:23


import django.core.serializers.json
from django.db import migrations, models
import json.decoder


class Migration(migrations.Migration):
    dependencies = [('H1stData', '0013_TextDataSet_in_db_text')]

    operations = [
        migrations.AddField(
            model_name='numpyarray',
            name='shape',
            field=models.JSONField(
                decoder=json.decoder.JSONDecoder,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text='Numpy Array Shape',
                verbose_name='Numpy Array Shape')),

        migrations.AlterField(
            model_name='numpyarray',
            name='dtype',
            field=models.JSONField(
                decoder=json.decoder.JSONDecoder,
                default=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text='Numpy Array Data Type(s)',
                verbose_name='Numpy Array Data Type(s)'))
    ]
