# Generated by Django 3.2.7 on 2021-10-11 21:28


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('H1stData', '0014_NumPyArray_shape')]

    operations = [
        migrations.CreateModel(
            name='LiveDataSource',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name='live_data_sources',
                     serialize=False,
                     to='H1stData.dataset'))
            ],

            options={
                'verbose_name': 'Live Data Source',
                'verbose_name_plural': 'Live Data Sources',
                'db_table': 'H1stData_LiveDataSource',
                'abstract': False,
                'default_related_name': 'live_data_sources',
                'base_manager_name': 'objects'
            },

            bases=('H1stData.dataset',)
        )
    ]
