# Generated by Django 3.1.13 on 2021-07-20 00:29


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('H1stData', '0005_optional_unique_name')
    ]

    operations = [
        # commenting out `RemoveField`
        # because of SQLite3 bug:
        # https://stackoverflow.com/questions/37955984/trying-to-migrate-in-django-1-9-strange-sql-error-django-db-utils-operationa
        # migrations.RemoveField(
        #    model_name='namedjsondataset',
        #    name='jsondataset_ptr'),
        # migrations.RemoveField(
        #     model_name='namednumpyarray',
        #     name='numpyarray_ptr'),
        # migrations.RemoveField(
        #     model_name='namedpandasdataframe',
        #     name='pandasdataframe_ptr'),
        # migrations.RemoveField(
        #     model_name='namedparquetdataset',
        #     name='parquetdataset_ptr'),
        # migrations.RemoveField(
        #     model_name='namedtfrecorddataset',
        #     name='tfrecorddataset_ptr'),

        migrations.DeleteModel(
            name='NamedCSVDataSet'),
        migrations.DeleteModel(
            name='NamedJSONDataSet'),
        migrations.DeleteModel(
            name='NamedNumPyArray'),
        migrations.DeleteModel(
            name='NamedPandasDataFrame'),
        migrations.DeleteModel(
            name='NamedParquetDataSet'),
        migrations.DeleteModel(
            name='NamedTFRecordDataSet')
    ]
