# Generated by Django 3.2.6 on 2021-08-19 07:35


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('H1stData', '0006_remove_NamedDataSet')]

    operations = [
        migrations.CreateModel(
            name='TextDataSet',

            fields=[
                ('dataset_ptr',
                 models.OneToOneField(
                     auto_created=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     parent_link=True,
                     primary_key=True,
                     related_name='text_data_sets',
                     serialize=False,
                     to='H1stData.dataset')),

                ('text',
                 models.TextField(
                     blank=True,
                     default=None,
                     help_text='Text',
                     null=True,
                     verbose_name='Text'))
            ],

            options={'verbose_name': 'Text Data Set',
                     'verbose_name_plural': 'Text Data Sets',
                     'db_table': 'H1stData_TextDataSet',
                     'abstract': False,
                     'default_related_name': 'text_data_sets',
                     'base_manager_name': 'objects'},

            bases=('H1stData.dataset',),
        )
    ]
